// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HittaHem.Mvc.Models
{
    [Table("Address")]
    public partial class Address
    {
        public Address()
        {
            Homes = new HashSet<Home>();
        }

        [Key]
        public int Address_Id { get; set; }
        [StringLength(50)]
        public string City { get; set; }
        [StringLength(50)]
        public string Municipality { get; set; }
        [StringLength(50)]
        public string Street { get; set; }

        [InverseProperty(nameof(Home.Address))]
        public virtual ICollection<Home> Homes { get; set; }
    }
}