// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HittaHem.Mvc.Models
{
    [Table("AssignmentForm")]
    public partial class AssignmentForm
    {
        public AssignmentForm()
        {
            Homes = new HashSet<Home>();
        }

        [Key]
        public int AssignmentForm_Id { get; set; }
        [StringLength(50)]
        public string AssignmentType { get; set; }

        [InverseProperty(nameof(Home.AssignmentForm))]
        public virtual ICollection<Home> Homes { get; set; }
    }
}