// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HittaHem.Mvc.Models
{
    [Table("Favourite")]
    public partial class Favourite
    {
        [Key]
        public int Home_Id { get; set; }
        [Key]
        public int User_Id { get; set; }
        [Column("Favourite")]
        public bool? Favourite1 { get; set; }

        [ForeignKey(nameof(Home_Id))]
        [InverseProperty("Favourites")]
        public virtual Home Home { get; set; }
        [ForeignKey(nameof(User_Id))]
        [InverseProperty("Favourites")]
        public virtual User User { get; set; }
    }
}