// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HittaHemEntityModels
{
    public class HomeViewing
    {
       
        public int Id { get; set; }  
        public DateTime ViewingDate { get; set; }
        public  Home Home { get; set; }
    }
}