// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HittaHemEntityModels
{
    public  class HomeImage
    {
     
        public int ImageId { get; set; }
        [Required]
        public byte[] Image { get; set; }

        public DateTime UploadingDate { get; set; }
        public Home HomeId { get; set; }
    }
}