// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HittaHemDemo.Models
{
    public  class HomeViewing
    {
        [Key]
        public int Id { get; set; }
        public int HomeId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime ViewingDate { get; set; }

        [ForeignKey(nameof(HomeId))]
        [InverseProperty("HomeViewings")]
        public virtual Home Home { get; set; }
    }
}