// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HittaHemEntityModels
{
    public  class Home
    {
        public int HomeId { get; set; }
       
        [Column(TypeName = "money")]
        public decimal? Price { get; set; }
        public string Description { get; set; }
        public int RoomAmount { get; set; }
        [Column(TypeName = "decimal(18, 0)")]
        public decimal LivingArea { get; set; }
        [Column(TypeName = "decimal(18, 0)")]
        public decimal? UninhabitableArea { get; set; }
        [Column(TypeName = "decimal(18, 0)")]
        public decimal? GardenArea { get; set; }
        [Column(TypeName = "date")]
        public DateTime? BuildYear { get; set; }
       
        [Required(ErrorMessage="Obligatoriskt fält")]
        public HousingType HousingTypeId { get; set; }      
     
        [Required(ErrorMessage = "Obligatoriskt fält")]
        public  Municipality MunicipalityId { get; set; }
        [Required(ErrorMessage = "Obligatoriskt fält")]
   
        public  OwnershipType OwnershipTypeId { get; set; }
       
        [Required(ErrorMessage= "Obligatoriskt fält")]
        public  Street StreetId { get; set; }

        public ICollection<HomeImage> HomeImages { get; set; } = new List<HomeImage>();
  
        public  ICollection<HomeViewing> HomeViewings { get; set; }=new List<HomeViewing>();

    }
}