// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HittaHemEntityModels
{
    public partial class HomeImage
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public byte[] Image { get; set; }
        public int HomeId { get; set; }
        [Column(TypeName = "date")]
        public DateTime UploadingDate { get; set; }

        [ForeignKey(nameof(HomeId))]
        [InverseProperty("HomeImages")]
        public virtual Home Home { get; set; }
    }
}