// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HittaHemEntityModels
{
    public  class HousingType
    {

     
        public int Id { get; set; }
        [Required]
        [StringLength(250)]
        public string Type { get; set; }
        public  ICollection<Home> Homes { get; set; }
    }
}