// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HittaHem.Mvc.Models
{
    [Table("HousingType")]
    public partial class HousingType
    {
        public HousingType()
        {
            Homes = new HashSet<Home>();
        }

        [Key]
        public int HousingType_Id { get; set; }
        [StringLength(50)]
        public string Type { get; set; }

        [InverseProperty(nameof(Home.HousingType))]
        public virtual ICollection<Home> Homes { get; set; }
    }
}