// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HittaHemEntityModels
{
    public  class HousingType
    {
        public HousingType()
        {
            Homes = new HashSet<Home>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(250)]
        public string Type { get; set; }

        [InverseProperty(nameof(Home.HousingType))]
        public virtual ICollection<Home> Homes { get; set; }
    }
}