// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HittaHemEntityModels
{
    public class InterestedUser
    {
        [Key]
        public int HomeId { get; set; }
   
        [StringLength(250)]
        public string UserId { get; set; }

        [ForeignKey(nameof(HomeId))]
        [InverseProperty("InterestedUsers")]
        public virtual Home Home { get; set; }
    }
}