// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HittaHemEntityModels
{
    public  class OwnershipType
    {    
        public int OwnershipTypeId { get; set; }
        [Required]
        [StringLength(250)]
        public string Name { get; set; }
        public ICollection<Home> Homes { get; set; } =new List<Home>(); 
    }
}