// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HittaHem.Mvc.Models
{
    [Table("User")]
    public partial class User
    {
        public User()
        {
            Favourites = new HashSet<Favourite>();
            Homes = new HashSet<Home>();
        }

        [Key]
        public int User_Id { get; set; }
        [Column("User")]
        [StringLength(50)]
        public string User1 { get; set; }
        [StringLength(50)]
        public string Admin { get; set; }
        [StringLength(50)]
        public string Agent { get; set; }
        public int? UserInfo_Id { get; set; }

        [ForeignKey(nameof(UserInfo_Id))]
        [InverseProperty("Users")]
        public virtual UserInfo UserInfo { get; set; }
        [InverseProperty(nameof(Favourite.User))]
        public virtual ICollection<Favourite> Favourites { get; set; }
        [InverseProperty(nameof(Home.User))]
        public virtual ICollection<Home> Homes { get; set; }
    }
}