// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HittaHem.Mvc.Models
{
    [Table("UserInfo")]
    public partial class UserInfo
    {
        public UserInfo()
        {
            Users = new HashSet<User>();
        }

        [Key]
        public int UserInfo_Id { get; set; }
        public int? User_Id { get; set; }
        [StringLength(100)]
        public string FirstName { get; set; }
        [StringLength(100)]
        public string LastName { get; set; }
        [StringLength(100)]
        public string Email { get; set; }
        public int? PhoneNumber { get; set; }

        [InverseProperty(nameof(User.UserInfo))]
        public virtual ICollection<User> Users { get; set; }
    }
}