// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HittaHem.Mvc.Models
{
    [Table("Viewing")]
    public partial class Viewing
    {
        public Viewing()
        {
            Homes = new HashSet<Home>();
        }

        [Key]
        public int Viewing_Id { get; set; }
        public int? Home_Id { get; set; }
        public int? User_Id { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ViewingDate { get; set; }

        [InverseProperty(nameof(Home.Viewing))]
        public virtual ICollection<Home> Homes { get; set; }
    }
}